### ISSUE TITLE
Update release on pypi

### ISSUE THREAD

**Issue by pjaol** [lobeck/flask-bower#11]
Howdy

Just ran into the issue with flask._compat and made the same modifications as #10 without realizing it, was about to fork and do the same pull request. 

Any chance this could be released to pypi? 

Thanks
Patrick

**Comment by lobeck** [comment]
Hey,

I'm sorry for the delay. A 2.0 has just been pushed to pypi containing that fix and a bunch of cleanups.

Can you give it a try?
